---
development:
  cloud_name: drjhf8tjm
  api_key: 916349682398511
  api_secret: paHNXwVuwM8R_Ah0FdvOhCnys3M
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: drjhf8tjm
  api_key: 916349682398511
  api_secret: paHNXwVuwM8R_Ah0FdvOhCnys3M
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: drjhf8tjm
  api_key: 916349682398511
  api_secret: paHNXwVuwM8R_Ah0FdvOhCnys3M
  enhance_image_tag: true
  static_file_support: false
